"""
Django settings for vk_dz project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False if os.environ.get('DEBUG', 'True') == 'False' else True

ALLOWED_HOSTS = [
    'django_app',
    'localhost',
    '127.0.0.1',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'debug_toolbar',
    'django_crontab',
    'django_ckeditor_5',
    'csp',
    'main',
]

INTERNAL_IPS = [
    '127.0.0.1',
    'localhost',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'csp.middleware.CSPMiddleware',
]

ROOT_URLCONF = 'vk_dz.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'main/templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vk_dz.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'lite': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    'main': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME', ''),
        'USER': os.environ.get('DB_USER', ''),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '3306'),
        'CONN_MAX_AGE': 300,
    }
}
DATABASES['default'] = DATABASES['lite']

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru-RU'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static_dev',
]
STATIC_ROOT = BASE_DIR / 'static'
MEDIA_URL = 'uploads/'
MEDIA_ROOT = BASE_DIR / 'uploads'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login and registration
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
REGISTRATION_OPEN = True

# Centrifugo
CENTRIFUGO_URL = os.environ.get('CENTRIFUGO_URL')
CENTRIFUGO_WS_URL = os.environ.get('CENTRIFUGO_WS_URL')
CENTRIFUGO_SECRET = os.environ.get('CENTRIFUGO_SECRET')
CENTRIFUGO_API_KEY = os.environ.get('CENTRIFUGO_API_KEY')

# Cache
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': '/var/tmp/django_cache',
    }
}

# Cron
CRONTAB_COMMAND_SUFFIX = '2>&1'
CRONJOBS = [
    ('0 0 * * 1', 'main.management.commands.update_cache.Command', '>> /var/log/update_cache.log'),
]

# Django-ckeditor for safety style questions and answers
CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': [
            'fontSize', 'fontFamily', 'fontColor', '|',
            'bold', 'italic', 'underline', 'strikethrough', '|',
            'link', 'blockQuote', 'codeBlock', '|',
            'bulletedList', 'numberedList', '|',
            'outdent', 'indent', '|',
            'imageUpload', '|',
            'undo', 'redo'
        ],
        'image': {
            'toolbar': [
                'imageStyle:inline', 'imageStyle:block', 'imageStyle:side'
            ]
        },
        'codeBlock': {
            'languages': [
                {'language': 'python', 'label': 'Python'},
                {'language': 'javascript', 'label': 'JavaScript'},
                {'language': 'html', 'label': 'HTML'},
                {'language': 'css', 'label': 'CSS'},
                {'language': 'php', 'label': 'PHP'},
                {'language': 'java', 'label': 'Java'},
                {'language': 'cpp', 'label': 'C++'},
                {'language': 'sql', 'label': 'SQL'},
                {'language': 'bash', 'label': 'Bash'},
                {'language': 'json', 'label': 'JSON'},
                {'language': 'xml', 'label': 'XML'},
                {'language': 'yaml', 'label': 'YAML'},
                {'language': 'markdown', 'label': 'Markdown'},
            ]
        },
        'fontSize': {
            'options': [10, 12, 14, 18, 20, 22]
        },
        'language': 'ru',
        'removePlugins': ['WordCount'],
    }
}
CKEDITOR_5_UPLOAD_FILE_TYPES = ['png', 'jpg', 'jpeg', 'gif', 'bmp', 'webp', ]
CKEDITOR_5_FILE_UPLOAD_PERMISSION = 'authenticated'

# CSP settings
CONTENT_SECURITY_POLICY = {
    'DIRECTIVES': {
        'default-src': ["'self'"],
        'script-src': ["'self'", "unpkg.com", "cdnjs.cloudflare.com", "stackpath.bootstrapcdn.com", "cdn.jsdelivr.net",
                       "'unsafe-inline'", "'unsafe-eval'"],
        'style-src': ["'self'", "'unsafe-inline'", "stackpath.bootstrapcdn.com", "cdn.jsdelivr.net"],
        'img-src': ["'self'", "data:", "https:", "blob:"],
        'font-src': ["'self'", "cdnjs.cloudflare.com", "stackpath.bootstrapcdn.com", "cdn.jsdelivr.net"],
        'connect-src': ["'self'", "ws:", "wss:", "127.0.0.1:8001"],
        'frame-src': ["'self'"],
        'media-src': ["'self'", "blob:"],

        'object-src': ["'none'"],
        'base-uri': ["'self'"],
        'frame-ancestors': ["'none'"],
        'form-action': ["'self'"],
        'report-uri': '/csp/'
    }
}

# Logging options
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'base': {
            'format': '[{levelname}] {asctime} {module} (line:{lineno}) | message: {message}',
            'style': '{',
        },
        'with_funcName': {
            'format': '[{levelname}] {asctime} {module}.{funcName} (line:{lineno}) | message: {message}',
            'style': '{',
        }
    },
    'handlers': {
        'file': {
            'formatter': 'base',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'debug.log',
        },
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'base',
        },
    },
    'loggers': {
        'custom_django': {
            'handlers': ['console'],
            'propagate': True,
            'level': 'INFO',
        },
        'default': {
            'handlers': ['file'],
            'propagate': True,
            'level': 'DEBUG',
        },
    },
}
