# Generated by Django 5.2.7 on 2025-10-23 08:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['-created_at'], name='answer_created_at_desc'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['-rating'], name='profile_rating_desc'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['-created_at'], name='question_created_at_desc'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['-rating'], name='tag_rating_desc'),
        ),
    ]
