# Generated by Django 5.2.7 on 2025-10-28 20:17

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_answer_answer_created_at_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
