# Generated by Django 5.2.7 on 2025-11-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_answer_text_alter_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='count_answers',
            field=models.IntegerField(default=0),
        ),
    ]
