# Generated by Django 5.2.7 on 2025-11-18 15:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_question_count_answers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['-rating', '-created_at'], name='answer_rating_created_at_desc'),
        ),
    ]
