# Generated by Django 5.2.7 on 2025-11-22 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_answer_answer_rating_created_at_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerlike',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='questionlike',
            old_name='active',
            new_name='is_active',
        ),
    ]
