# Generated by Django 5.2.7 on 2025-10-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_tag_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionlike',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
