# Generated by Django 5.2.7 on 2025-10-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_questionlike_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerlike',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
