# Generated by Django 5.2.7 on 2025-11-29 06:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_active_answerlike_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='answer',
            name='answer_created_at_desc',
        ),
        migrations.RemoveIndex(
            model_name='answer',
            name='answer_rating_created_at_desc',
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['-rating', '-is_correct', '-created_at'], name='answer_rating_created_at_desc'),
        ),
    ]
