# Generated by Django 5.2.7 on 2025-12-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='thumbnail_avatar',
            field=models.ImageField(default='default.png', upload_to='avatars/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default.png', upload_to='avatars/'),
        ),
    ]
