# Generated by Django 6.0 on 2025-12-30 11:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_profile_thumbnail_avatar_alter_profile_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='answer',
            name='answer_rating_created_at_desc',
        ),
        migrations.AlterField(
            model_name='profile',
            name='thumbnail_avatar',
            field=models.ImageField(default='default.png', upload_to='thumbnails/'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['-is_correct', '-rating', '-created_at'], name='answer_rating_created_at_desc'),
        ),
    ]
